### PR TITLE
Support for 4.08

### PR DESCRIPTION
**Pull request by xclerc**
(Joint work with @hhugo)

This is clearly a work-in-progress, but it sounds useful to
share it, at least to avoid duplication.

This versions allows to build with 4.08, but tests fails.
There are (at least) two pain points:

- the black magic discussed by @hhugo [here](https://github.com/realworldocaml/mdx/pull/86);
- the conversion of the condition `Ident.binding_time id >= 1000`
  (I thought it meant "is not builtin", but the `is_builtin` function
  I added is apparently not correct).

### CODE REVIEW

**Comment by gpetiot** [comment]
I didn't manage to build your branch with 4.08 (using this switch https://discuss.ocaml.org/t/ocaml-4-08-0-beta1-release/3325), did you push everything? Are you using specific package versions?

**Comment by xclerc** [comment]
I might have been using a patched compiler;
could you copy/paste the output of a failing build?

**Comment by gpetiot** [comment]
I have a long sequence of:
```
File "lib/migrate_ast.ml", line 34, characters 2-9:
Error (alert deprecated): module Ast_406
Access modules via the Migrate_parsetree toplevel module. Use Migrate_parsetree.Ast_406 instead.
```
When fixed, I get:
```
File "lib/top/mdx_top.ml", line 725, characters 27-57:
Error: Unbound module Toplevel_backend
```

**Comment by xclerc** [comment]
Indeed, sorry for that; I have pushed an additional
commit that should fix the build.

File: lib/top/mdx_top.ml [hunk 1]
```diff
@@ -661,7 +726,8 @@ let init ~verbose:v ~silent:s ~verbose_findlib () =
   Compmisc.init_path true;
   Toploop.toplevel_env := Compmisc.initial_env ();
   Sys.interactive := false;
-  patch_env ();
+  (* CR hheuzard: fixme *)
+  (* patch_env (); *)
```
Comment (trefis) [inline lib/top/mdx_top.ml]: What is happening here? I think this should be uncommented.

Comment (xclerc) [reply lib/top/mdx_top.ml]: You are right; https://github.com/realworldocaml/mdx/pull/121/commits/6856c56cd39074ea53288861ea283b867bca8209 restores the call.

**Comment by trefis** [comment]
Ping.
I think this can be merged now.

We've been using it internally at janestreet for a few days, and I have also been using it for testing merlin on 4.08.

**Comment by trefis** [comment]
And ping again.
4.08 is very likely to be merged before the end of the decade, and having mdx work from day one would be nice.

**Comment by samoht** [comment]
Thanks! Let me know if you need a new release.

**Comment by trefis** [comment]
Thanks!
Yes, a new release would be nice. So that I could setup travis tests for 4.08 on merlin's repository without having to pin this repository.
