### PR TITLE
Add support for OCaml 4.12

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by gpetiot** [comment]
Thanks, can you add the 4.12 check on the travis CI file?

**Comment by kit-ty-kate** [comment]
@gpetiot Is Travis still needed now that OCaml-CI is enabled btw?

**Review by gpetiot — APPROVED** [review]
Looks good! cc @NathanReb maybe it's time to remove the travis CI indeed

**Review by NathanReb — APPROVED** [review]
This looks good to me. @kit-ty-kate do you confirm you have been able to test this on 4.12 and it worked as intended?

I'll give it a go myself since it appears we can't rely on travis at all anymore and `ocaml-ci` isn't running 4.12 builds.

**Comment by kit-ty-kate** [comment]
I hadn't tried the tests but I now fixed the tests I could change.
There is an extra test that I'm guessing comes from a change in dune master (I have to use https://github.com/ocaml/dune/pull/3904 to be able to use `stdlib-shims`/`ppxlib`/...):
```
Done: 0/0 (jobs: 0)File "test/bin/mdx-rule/misc/duniverse-mode/dune.gen.expected", line 1, characters 0-0:
         git (internal) (exit 1)
(cd _build/default && /usr/bin/git --no-pager diff --no-index --color=always -u test/bin/mdx-rule/misc/duniverse-mode/dune.gen.expected test/bin/mdx-rule/misc/duniverse-mode/dune.gen)
diff --git a/test/bin/mdx-rule/misc/duniverse-mode/dune.gen.expected b/test/bin/mdx-rule/misc/duniverse-mode/dune.gen
index 4201b97..a2306f4 100644
--- a/test/bin/mdx-rule/misc/duniverse-mode/dune.gen.expected
+++ b/test/bin/mdx-rule/misc/duniverse-mode/dune.gen
@@ -9,6 +9,11 @@
   prelude.ml)
  (action
   (progn
-   (run ocaml-mdx test --prelude=prelude.ml --prelude-str
-     "#require \"prelude-str\"" %{x})
+   (run
+    ocaml-mdx
+    test
+    --prelude=prelude.ml
+    --prelude-str
+    "#require \"prelude-str\""
+    %{x})
    (diff? %{x} %{x}.corrected))))
```
I'm not sure how to make it work with both dune 2.7 and 2.8 (master) or if it's even desirable.

**Comment by NathanReb** [comment]
It appears to be a change in the formatting of the generated rule. `mdx rule` is deprecated so I don't put too much effort into this. I'll take a look to see if I can improve this test!

Worst case we could bump the minimum required dune version. Do you know when the 4.12 compatible dune version will be released?

**Comment by kit-ty-kate** [comment]
> Worst case we could bump the minimum required dune version. Do you know when the 4.12 compatible dune version will be released?

@rgrinberg do you have a rough idea?

**Comment by rgrinberg** [comment]
Early next week or late this week.

**Comment by gpetiot** [comment]
I have rebased the PR, the CI is alright but I have one test that doesn't pass locally: (lwt is installed of course, same version as on CI)
```diff
diff --git a/test/bin/mdx-test/expect/lwt/test-case.md b/test/bin/mdx-test/expect/lwt.actual
index 7544ce7..9a746fa 100644
--- a/test/bin/mdx-test/expect/lwt/test-case.md
+++ b/test/bin/mdx-test/expect/lwt.actual
@@ -2,15 +2,19 @@
 
 # #require "lwt"
+No such package: lwt
 # let x = Lwt.return 3
-val x : int Lwt.t = <abstr>
+Line 1, characters 9-19:
+Error: Unbound module Lwt
 ```
does anyone have the same error locally?

**Comment by NathanReb** [comment]
I just rebased this on top of master!

Giving it a spin locally and merging. Thanks for taking care of this and sorry for the delay!

**Comment by NathanReb** [comment]
Works like a charm, merging!
